---
- name: Checkout to deployment branch
  git:
    repo: "{{ repo }}"
    dest: "{{ app_dir }}"
    version: "{{ branch }}"
    update: yes

- name: Create backend .env file
  copy:
    content: "{{ backend_env }}"
    dest: "{{ app_dir }}/backend/.env"
    mode: '0600'

- name: Create frontend .env file
  copy:
    content: "{{ frontend_env }}"
    dest: "{{ app_dir }}/frontend/.env"
    mode: '0600'

- name: Copy docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ app_dir }}/docker-compose.yml"
    mode: '0644'

- name: Remove existing application images
  shell: |
    # Remove specific images using grep to match the repository
    docker images | grep "afeez511/frontend-dojodevops\|afeez511/backend-dojodevops" | awk '{print $1 ":" $2}' | xargs -r docker rmi -f
  ignore_errors: yes  # In case images are in use or don't exist

# - name: Pull fresh images
#   shell: docker compose pull
#   args:
#     chdir: "{{ app_dir }}"

- name: Stop existing containers
  shell: docker compose down
  args:
    chdir: "{{ app_dir }}"

- name: Start application stack
  shell: docker compose up -d
  args:
    chdir: "{{ app_dir }}"