---
- name: Checkout to deployment branch
  git:
    repo: "{{ repo }}"
    dest: "{{ app_dir }}"
    version: "{{ branch }}"
    update: yes

- name: Create backend .env file
  copy:
    content: "{{ backend_env }}"
    dest: "{{ app_dir }}/backend/.env"
    mode: '0600'

- name: Create frontend .env file
  copy:
    content: "{{ frontend_env }}"
    dest: "{{ app_dir }}/frontend/.env"
    mode: '0600'

- name: Copy docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ app_dir }}/docker-compose.yml"
    mode: '0644'


- name: Deploy application stack
  shell: |
    # Try to stop any existing application containers (won't fail if none exist)
    docker compose down || true

    # Safely try to remove old application images (won't fail if no images exist)
    docker images {{ DOCKERHUB_USERNAME }}/{{ FRONTEND_IMAGE }} -q | xargs -r docker rmi || true
    docker images {{ DOCKERHUB_USERNAME }}/{{ BACKEND_IMAGE }} -q | xargs -r docker rmi || true
    
    docker compose up -d --force-recreate
  args:
    chdir: "{{ app_dir }}"