---
- hosts: web_servers
  become: yes
  tasks:
    - name: Checkout to deployment branch
      git:
        repo: "{{ repo }}"
        dest: "{{ app_dir }}"
        version: "{{ branch }}"
        update: yes  # This ensures it pulls latest changes

    - name: Create backend .env file
      copy:
        content: "{{ backend_env }}"
        dest: "{{ app_dir }}/backend/.env"
        mode: '0600'

    - name: Create frontend .env file
      copy:
        content: "{{ frontend_env }}"
        dest: "{{ app_dir }}/frontend/.env"
        mode: '0600'

    - name: Deploy application stack
      docker_compose:
        project_src: "{{ app_dir }}"
        files:
          - docker-compose.yml
        state: present