---
- name: Clone the repository
  git:
    repo: "{{ repo }}"
    dest: "{{ app_dir }}"
    version: "{{ branch }}"

- name: Ensure the Traefik directory exists
  file:
    path: "{{ app_dir }}/traefik"
    state: directory
    mode: '0755'

- name: Create acme.json with proper permissions
  file:
    path: "{{ app_dir }}/traefik/acme.json"
    state: touch
    mode: '0600'

- name: Check if the data folder exists
  stat:
    path: "{{ app_dir }}/data"
  register: data_folder

- name: Ensure Loki data folder has the correct ownership and permissions
  block:
    - name: Change ownership of data folder for Loki
      command: chown -R 10001:10001 ./data
      args:
        chdir: "{{ app_dir }}"

    - name: Set permissions for the data folder
      command: chmod -R 755 ./data
      args:
        chdir: "{{ app_dir }}"
  when: data_folder.stat.exists

- name: Ensure app directories exist for backend and frontend
  file:
    path: "{{ app_dir }}/{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - backend
    - frontend

- name: Configure backend .env file using template
  template:
    src: "backend_env_template.j2"
    dest: "{{ app_dir }}/backend/.env"
    mode: '0644'

- name: Configure frontend .env file using template
  template:
    src: "frontend_env_template.j2"
    dest: "{{ app_dir }}/frontend/.env"
    mode: '0644'

- name: Configure application compose file using template
  template:
    src: "docker_compose_template.j2"
    dest: "{{ app_dir }}/docker-compose.yml"
    mode: '0644'

- name: Configure monitoring compose file using template
  template:
    src: "monitoring_stack_template.j2"
    dest: "{{ app_dir }}/monitoring-stack.yml"
    mode: '0644'